# Configure your game settings

#project name
name: $NAME

paths:
  images: assets/images
  sounds: assets/sounds
  levels: assets/levels
  src: src
  plugins: src/plugins
  lib: lib
  tests: tests

#types of files to be included in re.images, re.sounds, re.levels
types:
  images: png
  levels: json xml
  sounds: mp3 ogg

#files to ignore in the game
#regular expressions are allowed
src-ignore:


#files to ignore in entityjs source
#regular expressions are allowed
#save space by ignoring unused components
entity-ignore:
  socket.js
  
#although all files are compiled its
#you might have to include dependencies first
#regular expressions are allowed
order:
  