# Configure your game settings

width: 180
height: 180
canvas-id: game-canvas

canvas-border: false

#files to ignore in /scripts
scripts-ignore:
  
#specify files to be loaded first in /scripts
order:
  /tile.js$
  
#components to ignore in the entityjs source
#reduce file size by ignoring unused components
entity-ignore:
  socket
  wait
  group

#ignore tests in /tests
tests-ignore:
  